#! /bin/sh
# postinst script for rxvt-unicode
set -e
if [ "$1" = configure ]; then

    update-alternatives --install /usr/bin/rxvt rxvt \
        /usr/bin/urxvt 31
    update-alternatives --install /usr/bin/x-terminal-emulator \
        x-terminal-emulator /usr/bin/urxvt 11 \
        --slave /usr/share/man/man1/x-terminal-emulator.1.gz \
        x-terminal-emulator.1.gz /usr/share/man/man1/urxvt.1.gz
fi

#DEBHELPER#

exit 0


