.if !\n(.g .ab GNU tbl requires GNU troff.
.if !dTS .ds TS
.if !dTE .ds TE
.TH "RXVT-UNICODE" "1"  "X Version 11" "X Tools" 
.SH "NAME" 
urxvt (ouR XVT) \- a VT102 emulator for the X window system
.PP 
.SH "SYNOPSIS" 
.PP 
\fBurxvtd\fP
.PP
\fBurxvtc\fP [options] [\-e command [ args ]]
.PP 
.SH "DESCRIPTION" 
.PP 
\fBurxvtd\fP is a colour vt102 terminal
emulator intended as an \fIxterm\fP(1) replacement. \fBurxvtd\fP
implements the actual program that runs runs as daemon in background and
opens pseudo-ttys. You can run it from your X startup scripts, for
example.
.PP 
\fBurxvtc\fP is the client program of this duo. It connects to the
\fBurxvtd\fP daemon and requests a new terminal window. It
takes the same arguments as the \fBurxvt\fP program. 
.PP 
The positive aspect of this client-server solution is faster creation
time for terminal windows and a lot of saved memory. The other side is a
possible impact on stability - if the main program crashes, all
processes in the terminal windows are terminated.
.PP
.PP
.SH "SEE ALSO" 
.PP 
\fIurxvt\fP(1), \fIsh\fP(1), \fI/usr/share/doc/rxvt\-unicode/README.unicode\fP
.SH "AUTHOR"
Eduard Bloch <blade@debian.org>
.PP 
